config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments
  post "toggle_like" => "likes#toggle"

  get 'posts/index'
  root to: 'home#index'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :item
  validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, as: :item
  has_many :comments, dependent: :destroy
  validates :body,:title, presence: true
  belongs_to :user

  def self.generate_posts(n = 5, user = nil)
    user ||= User.last

    n.times do
        body = ' '+ Faker::Hobbit.quote
        post = Post.create!(
        title: Faker::Cat.breed,
        body: body,
        user: User.random_user
      )

      rand(8).times do
        post.comments.create(
          body: Faker::Hacker.say_something_smart,
          user: User.random_user
        )
      end

      rand(30).times do
        post.likes.create(
          user: User.random_user,
        )
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def is_admin?
    return true if role == "ADMIN"
  end

  # Check whether user is exist if not create one
  def self.create_user(email, role)
    new_password = SecureRandom.base64(16)
    temp_name = email.split("@")[0]
    user_attributes = {
      email: email,
      password: new_password,
      password_confirmation: new_password,
      role: role,
    }

    user = User.new(user_attributes)

    if user.save!
      UserMailer.welcome_email(
        email: user.email
      ).deliver_later
    end

    return user
  end

  def self.generate_users(n = 5, gender = "female")
    url = "https://randomuser.me/api?results=#{n}&gender=#{gender}"
    body = HTTP.get(url).parse

    body["results"].each do |person|
      hash = {}
      hash[:name] = person["name"]["first"] + " " + person["name"]["last"]
      hash[:email] = person["email"]
      o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
      string = (0...10).map { o[rand(o.length)] }.join
      hash[:password] = string
      hash[:image_url] = person["picture"]["large"]
      user = User.create! hash
    end
  end

  def liking?(item)
    likes.where(item: item).exists?
  end

  def toggle_like!(item)
    if like = likes.where(item: item).first
      like.destroy
    else
      likes.where(item: item).create!
    end
  end

  def self.random_user
    User.offset(rand User.count).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build comment_params

    if @comment.save
      @current_post = @comment.post
    else
      # xu ly error
    end

    respond_to do |f|
      f.html{ redirect_back(fallback_location: root_path) }
      f.js { render 'comment' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @comment =Comment.new
    @post = Post.new
    @posts = Post.paginate(per_page: "5", page: params[:page])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def toggle
    if params[:post_id]
      @item = Post.find params[:post_id]
     elsif params[:comment_id]
      @item = Comment.find(params[:comment_id])
    end
    current_user.toggle_like!(@item)

    respond_to do |f|
      f.html{ redirect_back(fallback_location: root_path) }
      f.js { render 'toggle' }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.with(user: @user).welcome_email.deliver_later

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(icon_name, text)
    content_tag(:span, fa_icon(icon_name), class: "icon") + content_tag(:span, text,class: "text-icon badge")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="col-sm-12" id="<%=dom_id cmt%>">
  <div class="panel panel-white cmt panel-shadow">
    <div class="cmt-heading">
      <div class="pull-left image">
        <img src="<%= cmt.user.image_url%>" class="img-circle avatar" alt="user profile image">
      </div>
      <div class="pull-left meta">
        <div class="cmt-body">
          <a href="#"><b><%= cmt.user.name %></b></a>
          <span class="card-text">
            <%= cmt.body %>
          </span>
        </div>
      </div>
    </div>
    <footer>
      <div class="meta">
        <%= link_to icon("heart-o"," #{cmt.likes.count} "), toggle_like_path(comment_id: cmt.id), class: "js-like-button #{'is-liked' if current_user.liking?(cmt)}", method: "post", remote: true %>
      </div>
    </footer>
  </div>
</div>

app/views/comments/_new_comment.html.erb
 <%= form_for @comment, remote: true, html: {autocomplete: "off"} do |f| %>
  <p>
    <%= f.hidden_field :post_id, value: post.id  %>
    <%= f.text_field :body, :placeholder => "Show me what you've got!", class: "new-comment" %>
  </p>
<% end %>

app/views/comments/comment.js.erb
$("#<%= dom_id @current_post %> .list-comments").append('<%= escape_javascript(render "comment", cmt: @comment) %>');
$("#<%= dom_id @current_post %> .new-comment").val("");

app/views/home/index.html.erb
<div id="carouselNatural" class="carousel slide" data-ride="carousel" >
  <div class="carousel-inner">
    <div class="carousel-item active"  style="padding: 60px;">
      <%= image_tag("na1.jpg", class: "d-block w-100", alt: "First slide", height: "600") %>
    </div>
    <div class="carousel-item" style="padding: 20px;">
      <%= image_tag("na2.jpg", class: "d-block w-100", alt: "Second slide", height: "600") %>
    </div>
    <div class="carousel-item" style="padding: 20px;">
      <%= image_tag("na3.jpg", class: "d-block w-100", alt: "Third slide", height: "600") %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselNatural" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselNatural" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container">
  <div class="page-header">
    <h1>Blog <small>for fun</small></h1>
  </div>
  <div class="row">
    <div class="col-md-8">
      <% @posts.each do |post| %>
        <%= render partial: "posts/post", locals: { post: post } %>
      <% end %>
      <div style="margin-top:20px" >
        <%= will_paginate @posts %>
      </div>
    </div>
    <aside class="col-md-4">
      <div class="card mb-3">
        <h3 class="card-header mb-3">Join Larion</h3>
        <form class="form-horizontal">
          <div class="form-group">
            <div class="col-sm-12">
              <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-12">
              <button type="submit" class="btn btn-primary">Join Us</button>
            </div>
          </div>
        </form>
      </div>
      <h3>Recent Posts</h3>
      <div class="list-group  mb-3">
        <a href="#" class="list-group-item active">
          <h4 class="list-group-item-heading">Top View</h4>
          <p class="list-group-item-text">
            Hello View &hellip;
          </p>
        </a>
        <a href="#" class="list-group-item">
          <h4 class="list-group-item-heading">Top Like</h4>
          <p class="list-group-item-text">
            Hello Like &hellip;
          </p>
        </a>
        <a href="#" class="list-group-item">
          <h4 class="list-group-item-heading">Top Comment</h4>
          <p class="list-group-item-text">
            Hello Sunny &hellip;
          </p>
        </a>
      </div>
    </aside>
  </div>
</div>

app/views/layouts/_top_navigation.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a href="/" class="m-brand__logo-wrapper">
        <%= image_tag("larion.png", height: "30") %>
      </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">News <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Training</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Our Products
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Health Care</a>
            <a class="dropdown-item" href="#">Ecommerce</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Mobil Application</a>
          </div>
        </li>
  <li class="nav-item">
          <a class="nav-link" href="#">Contact us</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeMailer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/top_navigation' %>
    <%= yield %>
  </body>
</html>

app/views/likes/toggle.js.erb
console.log("Hello sunny")
$("#<%= dom_id @item %>").find(".js-like-button").first().toggleClass("is-liked");
$("#<%= dom_id @item %>").find(".js-like-button .text-icon").first().text(" <%=@item.likes.count%> ")

app/views/posts/_post.html.erb
<article class="post" id="<%= dom_id post %>">
  <header>
    <h2>
      <a href="">
      <%= post.user.name %></a></h2>
    <div class="meta">
      Written by <span class="author"><%= post.user.name%></span> <span class="date"><%= time_ago_in_words post.updated_at %></span>
    </div>
  </header>
  <div class="entry-content">
    <a href="">
      <%= image_tag("sunny.png", class: "img-fluid", alt: "#{post.title}", size: "750x420")%>
    </a>
    <p><%= post.body %></p>
    <a href="#" class="btn btn-primary read-more">Read More <span class="glyphicon glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a>
  </div>
  <footer>
    <div class="meta">
      <%= link_to icon("heart-o"," #{post.likes.count} "), toggle_like_path(post_id: post.id), class: "js-like-button #{'is-liked' if current_user.liking?(post)}", method: "post", remote: true %>|
      <span class="comments"><span class="badge"><%= post.comments.count%></span> Comments</span>
    </div>
    <div class= "list-comments">
      <% post.comments.each do |cmt|  %>
        <%= render partial: "comments/comment", locals: {cmt: cmt} %>
      <% end %>
    </div>
    <div class="panel">
      <%= render partial: "comments/new_comment", locals: {post: post} %>
    </div>
  </footer>
</article>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>